pro 1.
ALTER SESSION SET NLS_TERRITORY = america;
SELECT SYSDATE FROM DUAL;

pro 2.
ALTER SESSION SET NLS_TERRITORY = america;
ALTER SESSION SET NLS_LANGUAGE = american;
SELECT TO_CHAR(SYSDATE,'DD-MON-YEAR DY') FROM DUAL;

PRO 3.
ALTER SESSION SET NLS_TERRITORY = america;
ALTER SESSION SET NLS_LANGUAGE = american;
SELECT TO_CHAR(SYSDATE,'FMDD-MON-YY DAY') FROM DUAL;

RPO 4.
SELECT SYSTIMESTAMP FROM DUAL;

PRO 5.
SELECT TO_CHAR(SYSTIMESTAMP,'tzr hh24:MI:SS.ff3') FROM DUAL;