ALTER SESSION SET NLS_TERRITORY = japan;
ALTER SESSION SET NLS_LANGUAGE = japanese;

PRO 1.1)
SELECT TO_DATE('2004/11/2','yyyy/MM/DD') FROM DUAL;

PRO 1.2)
SELECT TO_DATE('2004”N11ŒŽ2“ú','yyyy"”N"MM"ŒŽ"DD"“ú"') FROM DUAL;

PRO 2.
PRO 2.1)
SELECT  TO_CHAR(TO_DATE('99-11-2','YY-MM-DD'),'YYyy-MM-DD')
FROM DUAL;

PRO 2.2)
SELECT  TO_CHAR(TO_DATE('99-11-2','RR-MM-DD'),'YYyy-MM-DD')
FROM DUAL;

PRO 2.3)
SELECT  TO_CHAR(TO_DATE('49-11-2','RR-MM-DD'),'YYyy-MM-DD')
FROM DUAL;

PRO 2.4)
SELECT  TO_CHAR(TO_DATE('50-11-2','RR-MM-DD'),'YYyy-MM-DD')
FROM DUAL;

